### ISSUE TITLE
question over testing esxi_vib

### ISSUE THREAD

**Issue by rmtilson** [veksh/ansible-esxi#3]
Just curious on how you test the vib module? I was testing on a 7.0.3 hosts and it seems it was wanting to install a package even thought it is installed.

Looking at your notes I thought you might have copied the ansible source to /tmp on esxi. I attempted that but ran into issues. Just curious on how you tested the module.

**Comment by veksh** [comment]
I cannot remember exactly (it was 6 years ago), but looking at source it seems that if requested state is `latest` then the module tries to update VIB with `esxcli software vib update` and let `esxcli` decide if actual update is required (and sets `changed` flag if installed version had changed), so this behaviour is expected.

To test the module you could use something like 
`ansible -m esxi_vib 'name=esx-ui state=present' --check <your-esxi>`, 
no need to copy sources to esxi.

**Comment by rmtilson** [comment]
Hey thanks for the feedback, ill give that command a try and see what it outputs.
